---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: daanvm-nl-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - daanvm.nl
      - www.daanvm.nl

      # - christelmusic.nl
      # - www.christelmusic.nl

      secretName: daanvm-nl-tls

  rules:
    - host: "daanvm.nl"
      http: &daanvm_nl_http_rules
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: daanvm-nl
                port:
                  number: 80
    - host: "www.daanvm.nl"
      http: *daanvm_nl_http_rules

    # - host: "christelmusic.nl"
    #   http: &christelmusic_nl_http_rules
    #     paths:
    #       - pathType: Prefix
    #         path: "/"
    #         backend:
    #           service:
    #             name: christelmusic-nl
    #             port:
    #               number: 80
    # - host: "www.christelmusic.nl"
    #   http: *christelmusic_nl_http_rules
